### ISSUE TITLE
Test skips makes it possible to accidentally merge something that doesn't run the tests

### ISSUE THREAD

**Issue by tankefugl** [SINTEF/PySilCam#12]
I am wondering: Does having this check in place make it possible to accidentally merge something that doesn't run the tests? Imagine the following:

* I update the container, and accidentally remove the model path
* Tests are run, but since ROOTPATH = None, it will simply skip the tests
* GitHub Actions says that all is ✔️ , without mentioning the skippet tests unless I check the logs (unlikely!)

I get that you want to make it easy during development, but I wonder if it is better to be honest to the local developer and failing the tests because the testdata has not been configured.

_Originally posted by @tankefugl in https://github.com/SINTEF/PySilCam/pull/1_

Additional information:
https://pypi.org/project/pytest-error-for-skips/ may be what we are looking at, forcing all skips to be error on the CI, while allowing skips on other systems.

**Comment by emlynjdavies** [comment]
yes. Definitely sounds like what we want for the github actions. Something to add to the Dockerfile testing, perhaps?
