### ISSUE TITLE
Integrate Sphinx documentation with github pages so that it is available online

### ISSUE THREAD

**Issue by emlynjdavies** [SINTEF/PySilCam#31]
We can build Sphinx documentation (as described in the README). It is possible that this can be linked to github pages so that, for example, the latest master branch has online documentation that remains up-to-date. Then users can use the online documentation instead of having to rebuild sphinx for themselves.

**Comment by emlynjdavies** [comment]
https://www.docslikecode.com/articles/github-pages-python-sphinx/

https://github.com/ammaraskar/sphinx-action

**Comment by nepstad** [comment]
We need to make the sphix build use our Docker container, with the required packages installed. If we create an auto-built image in the future that can be used. See also this example: https://www.petefreitag.com/item/903.cfm.

**Comment by espenfl** [comment]
I would suggest you to use Read The Docs (RTD). As this is a public repo you can use their free service and link the repo. Very straightforward and efficient. Gives you the possibility to load docs from older tags etc. See for instance example here: https://github.com/aiidateam/aiida-core/blob/develop/.readthedocs.yml and the docs: https://aiida.readthedocs.io/en/latest/.

**Comment by emlynjdavies** [comment]
relevant for #37

**Comment by emlynjdavies** [comment]
Thanks @espenfl . I have quickly tried to set up an RTD project for this and coupled in this repo. I have have coupled it to this branch: https://github.com/SINTEF/PySilCam/tree/rtd-docs

It seems to build the main index page, but currently I am struggling to get the RTD builder to correctly install the conda environment for this repo so it can run the auto-sphinx documentation building.

**Comment by espenfl** [comment]
@emlynjdavies Great. Do you have a recipe of what is needed to build it locally?

**Comment by emlynjdavies** [comment]
@espenfl after installing the environment, then python setup.py build_sphinx does everything locally

that calls:
  sphinx-apidoc -f -o docs/source pysilcam/ --separate
  sphinx-build -b html ./docs/source ./docs/build

**Comment by espenfl** [comment]
Okey, but you need a specific conda setup and that is what is unclear how to configure at RTD?

**Comment by emlynjdavies** [comment]
yea - it seems that sphinx needs to import pysilcam, which can't be done unless the correct dependencies are installed.

**Comment by emlynjdavies** [comment]
I have put:

```
conda:
    environment: environment.yml
```

in the .readthedocs.yaml to try to solve this, but didn't work

**Comment by espenfl** [comment]
> yea - it seems that sphinx needs to import pysilcam, which can't be done unless the correct dependencies are installed.

Okey, maybe this can help you a bit on the way (the way we do it, but regular Python): https://github.com/aiida-vasp/aiida-vasp/blob/develop/doc/requirements.txt and then https://github.com/aiida-vasp/aiida-vasp/blob/develop/readthedocs.yml. We need to install AiiDA as we need a special Sphinx extension from there to be able to complete autodocs etc. Except from your conda situation I think that use case is pretty similar (but packages are different of course).

I have personally never done Conda in RTD, but docs mentions it is fully supported.

Does the logs mention something useful? Sometimes when I have been stuck I have generated an RTD container and built the docs there to have full control of what is going on.
