### ISSUE TITLE
Improve image viewers

### ISSUE THREAD

**Issue by davidrwilliamson** [SINTEF/PySilCam#32]
The current viewer for playing back images in the GUI is quite awkward and buggy. I'd like to fix or improve the following:

- The pause feature is unreliable and will move frames when the mouse is moving or there is keyboard input. I think this is an issue with PyGame events
- The live viewer and saved file viewers are somewhat different in features, for instance the live viewer lets you save out images to bitmap (rather than .silc). I think these two could be functionally the same, or even use mostly the same code?
- I'd like to be able to annotate frames of interest and save out a list of the annotated frames. This is useful in reviewing video and marking for instance frames that contain interesting particles or that you'd like to use for NN training.
- The viewers should be able to open image formats other than RGB8, such as Bayer8. This probably needs its own issue, as it affects a lot of other areas too. See issue #35 

There is also the shell script, silc_monitor.py, for previewing images as they are acquired. I'm not sure to what extent this can/should be brought more in line with the other two viewers.

**Comment by davidrwilliamson** [comment]
Also to fix: the viewer in guicalc (at least) does not scale properly to content and the window can't be resized.

**Comment by espenfl** [comment]
On Apr 23, 2020 15:56, David Williamson <notifications@github.com> wrote:
Also to fix: the viewer in guicalc (at least) does not scale properly to content and the window can't be resized.
