### ISSUE TITLE
Error creating conda env. probably due to pip

### ISSUE THREAD

**Issue by WillRNaylor** [SINTEF/PySilCam#39]
**Describe the bug**
An error occurs when creating the `silcam` conda environment, where packages that would be installed by pip aren't found

**To Reproduce**
Working on a mac using conda version 4.8.3 and having completely deleting the `silcam` environment creating `silcam` from the .yml file with:

`conda env create -f environment.yml --force`

I get the following output:

```
conda env create -f environment.yml --force
Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies.  Conda may not use the correct pip to install your packages, and they may end up in the wrong place.  Please add an explicit pip dependency.  I'm adding one for you, but still nagging you.
Collecting package metadata (repodata.json): done
Solving environment: done
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Ran pip subprocess with arguments:
['/Users/odin/anaconda3/envs/silcam/bin/python', '-m', 'pip', 'install', '-U', '-r', '/Users/odin/Sintef/SilCam/PySilCam/condaenv._yurf74i.requirements.txt']
Pip subprocess output:

Pip subprocess error:
Traceback (most recent call last):
  File "/Users/odin/anaconda3/envs/silcam/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/odin/anaconda3/envs/silcam/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/odin/anaconda3/envs/silcam/lib/python3.5/site-packages/pip/__main__.py", line 16, in <module>
    from pip._internal import main as _main  # noqa
  File "/Users/odin/anaconda3/envs/silcam/lib/python3.5/site-packages/pip/_internal/__init__.py", line 42, in <module>
    from pip._internal import cmdoptions
  File "/Users/odin/anaconda3/envs/silcam/lib/python3.5/site-packages/pip/_internal/cmdoptions.py", line 16, in <module>
    from pip._internal.index import (
  File "/Users/odin/anaconda3/envs/silcam/lib/python3.5/site-packages/pip/_internal/index.py", line 25, in <module>
    from pip._internal.download import HAS_TLS, is_url, path_to_url, url_to_path
  File "/Users/odin/anaconda3/envs/silcam/lib/python3.5/site-packages/pip/_internal/download.py", line 39, in <module>
    from pip._internal.utils.glibc import libc_ver
  File "/Users/odin/anaconda3/envs/silcam/lib/python3.5/site-packages/pip/_internal/utils/glibc.py", line 3, in <module>
    import ctypes
  File "/Users/odin/anaconda3/envs/silcam/lib/python3.5/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: dlopen(/Users/odin/anaconda3/envs/silcam/lib/python3.5/lib-dynload/_ctypes.cpython-35m-darwin.so, 2): Library not loaded: @rpath/libffi.6.dylib
  Referenced from: /Users/odin/anaconda3/envs/silcam/lib/python3.5/lib-dynload/_ctypes.cpython-35m-darwin.so
  Reason: image not found


CondaEnvException: Pip failed
```

**Expected behavior**
Obviously I would expect this to work, with some success message from pip and then conda.

**Additional context**
The conda env is created (partially, I believe all the non-pip packages are installed correctly, although this isn't tested), so I can go into it and find which version of pip was used:

```
pip                       10.0.1                   py35_0    anaconda
```
Which seems to be a default pip for python 3.5.

**Comment by emlynjdavies** [comment]
would be interesting to see if this is a mac thing, or if you get the same problem in linux.

**Comment by nepstad** [comment]
> would be interesting to see if this is a mac thing, or if you get the same problem in linux.

The automated tests would pick it up in that case, I think. The observed error appears to be caused by the version of libffi that gets installed on mac. In the Docker environment, we have version 3.2.1, but on mac we get version 3.3, based on the same environment.yml file. Installing version 3.2.1 explicitly on mac seems to fix the problem.

**Comment by WillRNaylor** [comment]
I have tested Raymond's above message, and I can concur that it works.

So adding:
```
    - pip=10.0.1
    - libffi=3.2.1

```
to the environment.yml file could be done? Note that I tested this locally, and it actually matters the oder in which this is added, it worked when directly after the python install, but not at the end. Also, the pip version isn't actually needed, but maybe nice.

**Comment by emlynjdavies** [comment]
ok. cool. if it works, then just go ahead and make a PR.

**Comment by emlynjdavies** [comment]
I had an issue with libffi this morning on a windows machine. had to install via conda-forge. Anyone with a Windows machine who can check?
