### ISSUE TITLE
Installation fails on windows with NVIDIA drivers

### ISSUE THREAD

**Issue by emlynjdavies** [SINTEF/PySilCam#41]
**Describe the bug**
tensorflow gpu gets automatically installed due to NVIDIA drivers being detected, and then doesn't work.

**To Reproduce**
install from environment file on a windows machine that has NVIDIA drivers.

**Expected behavior**
importing tesnorflow causes an error in imp

**Additional context**
solved by installing tensorflow-mkl (version 1.10.0) via pip, and skimage version 0.15.0 also via pip.

environment file should be fixed to handle this situation

**Comment by emlynjdavies** [comment]
@aya-saad Is this the same issue you had in March?

**Comment by aya-saad** [comment]
no 
I had a different issue with the scipy and scikit on my pc. still have this issue I resolve it usually by installing a different version of scikit

**Comment by emlynjdavies** [comment]
> no
> I had a different issue with the scipy and scikit on my pc. still have this issue I resolve it usually by installing a different version of scikit

After changing to this version of tensorflow, we also had to use scikit image 0.15.0 instead of 0.14.0

**Comment by emlynjdavies** [comment]
using skimage 0.15.0 causes an imresize error

**Comment by emlynjdavies** [comment]
recent updates have fixed many installation issues.
