### ISSUE TITLE
External users cannot push (403 error) or edit online without forking.

### ISSUE THREAD

**Issue by emlynjdavies** [SINTEF/PySilCam#8]
External users should have push writes by default (so long as they have a github ID).

**Comment by tankefugl** [comment]
It seems that the following approaches are allowed:

* Invite each user individually to the repository, which will grant write access, OR
* Create a team of `pysilcam-users` that users can be invited into, where the team is given write access (separated from admins)

Regardless, users can fork and make pull requests without being given access.

The Fork + Pull Request is the dominant method for working together on things on GitHub without being a part of the team, and repositories elsewhere use that a lot. It is an elegant way of both supporting organisations that wants the final control themselves (such as SINTEF) and allow open contributions without giving access.

I suggest we invite our known collaborators into a pysilcam-users team and sticking with Fork+PR for uknown collaborators, aligning ourselves with the common GitHub way of doing things.

**Comment by emlynjdavies** [comment]
Ok. Sounds like a good plan!
