### ISSUE TITLE
Implement a versioning system for PySilcam

### ISSUE THREAD

**Issue by nepstad** [SINTEF/PySilCam#86]
After #24, we are tagging some output with metadata including PySilcam version, however, at present we have no process in place to decide when and how to increment the version number (stuck for now at 0.1.0). We should consider the alternatives and decide on a process, for instance using git tags.

Semantic versioning scheme: https://semver.org/

See: https://packaging.python.org/guides/single-sourcing-package-version/
See also: https://github.com/TobiasAsk/release-experiment

**Comment by emlynjdavies** [comment]
increment of last number in verion should be done on each merged PR

**Comment by WillRNaylor** [comment]
@emlynjdavies Should this issue be closed now? We can always add a new one later if we outgrow our current system.

**Comment by emlynjdavies** [comment]
Yes, I think this can be closed. We can check what @nepstad thinks, since he opened this case.

**Comment by nepstad** [comment]
Issue resolved by versioning system now in place.
